# Generated by Django 5.0.6 on 2024-05-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('apellido', models.CharField(max_length=150)),
                ('fecha_de_nacimiento', models.DateField(blank=True, null=True)),
                ('año_curso', models.PositiveBigIntegerField(unique=True)),
            ],
        ),
    ]
