# Generated by Django 5.0.6 on 2024-05-23 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumno', '0001_initial'),
        ('docente', '0001_initial'),
        ('materia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='docente_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='docente.docente'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='materia_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='materia.materia'),
        ),
    ]
