# Generated by Django 5.0.6 on 2024-05-26 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Año',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumno.alumno')),
                ('año', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumno.año')),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='año',
            field=models.ManyToManyField(through='alumno.Inscripcion', to='alumno.año'),
        ),
    ]
