# Generated by Django 5.0.6 on 2024-05-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0003_año_inscripcion_alumno_año'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='año_curso',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
