# Generated by Django 5.0.6 on 2024-05-26 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0003_año_inscripcion_alumno_año'),
        ('docente', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='año',
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumno.año')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docente.docente')),
            ],
        ),
        migrations.AddField(
            model_name='docente',
            name='año',
            field=models.ManyToManyField(through='docente.Curso', to='alumno.año'),
        ),
    ]
