# Generated by Django 5.0.6 on 2024-05-26 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0003_año_inscripcion_alumno_año'),
        ('docente', '0004_curso_materia'),
        ('materia', '0002_alter_materia_alumnos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='año',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alumno.año'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='docente.docente'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='materia.materia'),
        ),
    ]
