# Generated by Django 5.0.6 on 2024-05-30 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0005_alter_curso_año_alter_curso_docente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='año',
        ),
        migrations.AddField(
            model_name='docente',
            name='año',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
