# Generated by Django 5.0.6 on 2024-05-31 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0006_remove_docente_año_docente_año'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='año',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='año',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='materia_id',
        ),
        migrations.AddField(
            model_name='docente',
            name='materia',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
