# Generated by Django 5.0.6 on 2024-05-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0002_initial'),
        ('materia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='alumnos',
            field=models.ManyToManyField(blank=True, null=True, to='alumno.alumno'),
        ),
    ]
