# Generated by Django 5.0.6 on 2024-05-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0003_año_inscripcion_alumno_año'),
        ('materia', '0002_alter_materia_alumnos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='alumnos',
            field=models.ManyToManyField(to='alumno.alumno'),
        ),
    ]
