# Generated by Django 5.0.6 on 2024-05-26 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0003_alter_materia_alumnos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='alumnos',
        ),
    ]
