# Generated by Django 5.0.6 on 2024-05-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0004_remove_materia_alumnos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='codigo',
        ),
        migrations.AddField(
            model_name='materia',
            name='año_materia',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
