# Generated by Django 5.0.6 on 2024-05-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0005_remove_materia_codigo_materia_año_materia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='docente',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
