# Generated by Django 5.0.6 on 2024-05-31 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0008_alter_materia_docente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
    ]
